sudo: false

env:
  ELM_VERSION=0.17.0

language: node_js
node_js:
  "6"

cache:
  directories:
    - elm-stuff/build-artifacts
    - tests/elm-stuff/build-artifacts

install:
  - npm -g install elm@$ELM_VERSION elm-test
  - make deps
script: make all
